### ISSUE TITLE
NetSuite Docs have dead references

### ISSUE THREAD

**Issue by marmani** [mulesoft/docs-connectors#2271]
Hello,

In all of the files called `nav.adhoc` in the paths `mulesoft/docs-connectors/netsuite/11.X/modules/ROOT`, all of the links result in 404 errors. This is a request to update the pointers in that documentation to valid resources.

For example: https://github.com/mulesoft/docs-connectors/blob/latest/netsuite/11.7/modules/ROOT/netsuite-studio-configure.adoc

Thank you.

**Comment by sathya0** [comment]
Hi @marmani! It seems to be working fine on my end. The path should have ROOT/pages instead of just ROOT. Can you try this link? https://github.com/mulesoft/docs-connectors/blob/latest/netsuite/11.7/modules/ROOT/pages/netsuite-studio-configure.adoc

**Comment by sathya0** [comment]
Hey @marmani! That link doesn't work as it should be ROOT/pages rather than just ROOT, for example, it should be https://github.com/mulesoft/docs-connectors/blob/latest/netsuite/11.7/modules/ROOT/pages/netsuite-studio-configure.adoc  instead of https://github.com/mulesoft/docs-connectors/blob/latest/netsuite/11.7/modules/ROOT/netsuite-studio-configure.adoc. None of our nav.adoc point to the right page since we link the pages in a specific way that renders properly on our public docs site. For the correct links to the documentation, please refer to documentation under the /pages path. https://github.com/mulesoft/docs-connectors/tree/latest/netsuite/11.7/modules/ROOT/pages or on our public docs site https://docs.mulesoft.com/netsuite-connector/11.7/
