### ISSUE TITLE
Documentation unclear/incomplete on Salesforce connector index page

### ISSUE THREAD

**Issue by jasalltime** [mulesoft/docs-connectors#2393]
In the "Before You Begin" Section regarding the last point, "If you are using OAuth authentication, the namespace and schema location", seems incomplete.

Page URI: https://docs.mulesoft.com/salesforce-connector/10.18/

![image](https://github.com/mulesoft/docs-connectors/assets/88364383/9daf25c1-0e5a-49d2-86bb-f3a317024d6b)

**Comment by sathya0** [comment]
Thanks for reporting this @jasalltime. We will look into this.

**Comment by sathya0** [comment]
I believe the idea is that before creating an app, you must have the namespace and schema location (if you are using OAuth authentication). Let me verify if this is accurate, and if so, we will reword for clarity

**Comment by jasalltime** [comment]
It'd be great if you verify. Thank you for the reply.

**Comment by sathya0** [comment]
Hey @jasalltime - we verified the information and updated the docs accordingly. You can see the changes in [this PR](https://github.com/mulesoft/docs-connectors/pull/2399) or on the [docs site](https://docs.mulesoft.com/salesforce-connector/10.18/) as it is now updated. The issue was that we had the accurate info in the 10.6 version but it never got carried over to 10.7 and later. The info is accurate now for all versions. Thank you for reporting this!

**Comment by jasalltime** [comment]
Thanks @sathya0 for your efforts. Now I am closing the issue.
